import express from "express";
import { connectDB, mssql } from "../config/db.js";

const router = express.Router();

// Helpers
const ok = (res, data) => res.json(data);
const err500 = (res, msg, err) => { console.error(msg, err); res.status(500).json({ error: msg }); };
const toFloat = (v) => { if (v === undefined || v === null || v === "") return null; const s = typeof v === "string" ? v.replace(/,/g, ".") : v; const n = Number.parseFloat(s); return Number.isNaN(n) ? null : n; };
const toInt = (v) => { if (v === undefined || v === null || v === "") return null; const n = Number.parseInt(v, 10); return Number.isNaN(n) ? null : n; };

// TPProcesso
router.get("/tpprocesso", async (_req, res) => { try { const pool = await connectDB(); const result = await pool.request().query(`SELECT Id, Referencia, Cliente, TempoTotal, CustoTotal, CronoColaborador, CronoTamanho, CronoData, CronoCronometrista, CronoDescritista, CustoMinuto, CreateAt FROM IMAGEMUNIFORMES_pBI.dbo.TPProcesso ORDER BY Id DESC`); ok(res, result.recordset); } catch (e) { err500(res, "Erro ao listar TPProcesso", e); } });
router.get("/tpprocesso/:id", async (req, res) => { try { const pool = await connectDB(); const result = await pool.request().input("id", mssql.Int, toInt(req.params.id)).query(`SELECT Id, Referencia, Cliente, TempoTotal, CustoTotal, CronoColaborador, CronoTamanho, CronoData, CronoCronometrista, CronoDescritista, CustoMinuto, CreateAt FROM IMAGEMUNIFORMES_pBI.dbo.TPProcesso WHERE Id=@id`); if (result.recordset.length === 0) return res.status(404).json({ error: "TPProcesso não encontrado" }); ok(res, result.recordset[0]); } catch (e) { err500(res, "Erro ao buscar TPProcesso", e); } });
router.put("/tpprocesso/:id", async (req, res) => { try { const pool = await connectDB(); const id = toInt(req.params.id); const fields = req.body || {}; const r = pool.request(); r.input('id', mssql.Int, id); const fieldTypes = { Referencia: mssql.VarChar(99), Cliente: mssql.VarChar(99), TempoTotal: mssql.Float, CustoTotal: mssql.Float, CronoColaborador: mssql.VarChar(99), CronoTamanho: mssql.VarChar(10), CronoData: mssql.DateTime, CronoCronometrista: mssql.VarChar(99), CronoDescritista: mssql.VarChar(99), CustoMinuto: mssql.Float }; const setClauses = []; Object.entries(fields).forEach(([k, v]) => { if (fieldTypes[k]) { const value = k.includes("Total") || k.includes("Minuto") ? toFloat(v) : v; r.input(k, fieldTypes[k], value !== '' ? value : null); setClauses.push(`${k}=@${k}`); } }); if (setClauses.length === 0) return res.status(400).json({ error: "Nenhum campo para atualizar" }); const q = `UPDATE IMAGEMUNIFORMES_pBI.dbo.TPProcesso SET ${setClauses.join(', ')} WHERE Id=@id; SELECT * FROM IMAGEMUNIFORMES_pBI.dbo.TPProcesso WHERE Id=@id`; const rs = await r.query(q); ok(res, rs.recordset[0] || null); } catch (e) { err500(res, "Erro ao atualizar TPProcesso", e); } });

// TPCalculadora
router.get("/tpcalculadora", async (_req, res) => { try { const pool = await connectDB(); const result = await pool.request().query(`SELECT Id, ProcessoId, Modelo, Descricao, Tecido, PartePeca, Variacao, TempoPadrao, Desconto, CreateAt FROM IMAGEMUNIFORMES_pBI.dbo.TPCalculadora ORDER BY Id DESC`); ok(res, result.recordset); } catch (e) { err500(res, "Erro ao listar TPCalculadora", e); } });
router.get("/tpcalculadora/:id", async (req, res) => { try { const pool = await connectDB(); const result = await pool.request().input("id", mssql.Int, toInt(req.params.id)).query(`SELECT Id, ProcessoId, Modelo, Descricao, Tecido, PartePeca, Variacao, TempoPadrao, Desconto, CreateAt FROM IMAGEMUNIFORMES_pBI.dbo.TPCalculadora WHERE Id=@id`); if (result.recordset.length === 0) return res.status(404).json({ error: "TPCalculadora não encontrado" }); ok(res, result.recordset[0]); } catch (e) { err500(res, "Erro ao buscar TPCalculadora", e); } });
router.put("/tpcalculadora/:id", async (req, res) => { try { const pool = await connectDB(); const id = toInt(req.params.id); const fields = req.body || {}; const r = pool.request(); r.input('id', mssql.Int, id); const fieldTypes = { ProcessoId: mssql.Int, Modelo: mssql.VarChar(99), Descricao: mssql.VarChar(255), Tecido: mssql.VarChar(99), PartePeca: mssql.VarChar(99), Variacao: mssql.VarChar(99), TempoPadrao: mssql.Float, Desconto: mssql.Float }; const setClauses = []; Object.entries(fields).forEach(([k, v]) => { if (fieldTypes[k]) { const value = k.includes("Tempo") || k.includes("Desconto") ? toFloat(v) : toInt(v); r.input(k, fieldTypes[k], value !== '' ? value : null); setClauses.push(`${k}=@${k}`); } }); if (setClauses.length === 0) return res.status(400).json({ error: "Nenhum campo para atualizar" }); const q = `UPDATE IMAGEMUNIFORMES_pBI.dbo.TPCalculadora SET ${setClauses.join(', ')} WHERE Id=@id; SELECT * FROM IMAGEMUNIFORMES_pBI.dbo.TPCalculadora WHERE Id=@id`; const rs = await r.query(q); ok(res, rs.recordset[0] || null); } catch (e) { err500(res, "Erro ao atualizar TPCalculadora", e); } });

// TPDescritivo
router.get("/tpdescritivo", async (_req, res) => { try { const pool = await connectDB(); const result = await pool.request().query(`SELECT Id, ProcessoId, AtividadeNome, Maquina, Tempo, TempoCentesimal, PartePeca, CreateAt FROM IMAGEMUNIFORMES_pBI.dbo.TPDescritivo ORDER BY Id DESC`); ok(res, result.recordset); } catch (e) { err500(res, "Erro ao listar TPDescritivo", e); } });
router.get("/tpdescritivo/:id", async (req, res) => { try { const pool = await connectDB(); const result = await pool.request().input("id", mssql.Int, toInt(req.params.id)).query(`SELECT Id, ProcessoId, AtividadeNome, Maquina, Tempo, TempoCentesimal, PartePeca, CreateAt FROM IMAGEMUNIFORMES_pBI.dbo.TPDescritivo WHERE Id=@id`); if (result.recordset.length === 0) return res.status(404).json({ error: "TPDescritivo não encontrado" }); ok(res, result.recordset[0]); } catch (e) { err500(res, "Erro ao buscar TPDescritivo", e); } });
router.put("/tpdescritivo/:id", async (req, res) => { try { const pool = await connectDB(); const id = toInt(req.params.id); const fields = req.body || {}; const r = pool.request(); r.input('id', mssql.Int, id); const fieldTypes = { ProcessoId: mssql.Int, AtividadeNome: mssql.VarChar(99), Maquina: mssql.VarChar(99), Tempo: mssql.Time, TempoCentesimal: mssql.Float, PartePeca: mssql.VarChar(99) }; const setClauses = []; Object.entries(fields).forEach(([k, v]) => { if (fieldTypes[k]) { const value = k === 'TempoCentesimal' ? toFloat(v) : (k === 'ProcessoId' ? toInt(v) : v); r.input(k, fieldTypes[k], value !== '' ? value : null); setClauses.push(`${k}=@${k}`); } }); if (setClauses.length === 0) return res.status(400).json({ error: "Nenhum campo para atualizar" }); const q = `UPDATE IMAGEMUNIFORMES_pBI.dbo.TPDescritivo SET ${setClauses.join(', ')} WHERE Id=@id; SELECT * FROM IMAGEMUNIFORMES_pBI.dbo.TPDescritivo WHERE Id=@id`; const rs = await r.query(q); ok(res, rs.recordset[0] || null); } catch (e) { err500(res, "Erro ao atualizar TPDescritivo", e); } });

export default router;
